---
# Включаем маршрутизацию транзитных пакетов
- name: Setup forward net.ipv4.conf.all.forwarding
  ansible.builtin.sysctl:
    name: net.ipv4.conf.all.forwarding
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Setup forward net.ipv4.ip_forward
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Set net.ipv4.conf.all.arp_filter to 1
  ansible.builtin.sysctl:
    name: net.ipv4.conf.all.arp_filter
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Set net.ipv4.conf.all.arp_ignore to 2
  ansible.builtin.sysctl:
    name: net.ipv4.conf.all.arp_ignore
    value: "2"
    sysctl_set: yes
    state: present
    reload: yes